---
# Weekly VM update shared ansible tasks
# Fix git config for older templates
- name: git config name
  git_config:
    name: user.name
    scope: global
    value: "J. Doe (https://devcenter.bitrise.io/builds/setting-your-git-credentials-on-build-machines/)"
- name: git config email
  git_config:
    name: user.email
    scope: global
    value: "please-set-your-email@bitrise.io"

- name: Ensure /Library/LaunchDaemons/ exists
  file:
    path: /Library/LaunchDaemons/
    state: directory
    owner: root
    group: wheel
    mode: "0644"
  become: true

# Copy these two plist file to incrase Open File Descriptos
- name: "Setup open-file limit"
  copy:
    src: limit.maxfiles.plist
    dest: /Library/LaunchDaemons/limit.maxfiles.plist
    owner: root
    group: wheel
    mode: "0644"
  become: true

- name: "Setup max-process limit"
  copy:
    src: limit.maxproc.plist
    dest: /Library/LaunchDaemons/limit.maxproc.plist
    owner: root
    group: wheel
    mode: "0644"
  become: true

# ----------------------------------------
# --- pre-installed tool cache updates ---
# ----------------------------------------

# curl used in place of get_url or uri module
# Shells that use pipes should set the pipefail option
- name: "firebase (CLI)"  # noqa 303 306
  shell: bash -l -c "curl -sL firebase.tools | bash"

# We still have permission issue
- name: Fixed pip install issue
  shell: bash -l -c "sudo -H python3 -m pip install --force-reinstall pip"

# ---------------------------------
# --- Community requested tools ---
# ---------------------------------

# Gems
- name: Install additional gems
  gem:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    executable: "$HOME/.rbenv/shims/gem"
    user_install: false
  with_items:
    - "{{ gem_packages }}"

# Tools installed from artifacts
- name: Install tools from artifacts
  include_tasks:
    file: tools-from-artifacts.yml

# Taps
- name: "Set up wix/brew"
  homebrew_tap:
    name: wix/brew
    state: present

# Kegs
- name: Install additional brew kegs
  homebrew:
    name: "{{ item.name }}"
    state: present
    update_homebrew: true
  with_items:
    - "{{ brew_packages }}"

- name: Install danger-swift below 11.4.x
  homebrew:
    name: "danger/tap/danger-swift"
    state: present
    update_homebrew: false
  when: xcode_version not in danger_swift_unsupported_versions

# ----------------------------------------
# --- Cleanup ---
# ----------------------------------------

# Remove tmp / test dirs inside the HOME directory
#  * DerivedData:
#     remove the DerivedData content generated by the Bitrise Stack tester sample apps
#     (built during Stack prepare, to validate the Xcode setup)
#  * Xcode "components" (simulators) installer Download Cache dir:
#     Xcode stores the simulator installers here, and it never cleans them up for some reason.

- name: Remove tmp and test dirs inside the HOME directory
  file:
    path: "$HOME/{{ item.fold_path }}"
    state: absent
  with_items:
    - { fold_path: 'Library/Developer/Xcode/DerivedData' }
    - { fold_path: 'Library/Caches/com.apple.dt.Xcode/Downloads' }

- name: Brew cleanup weekly
  include_role:
    name: brew-cleanup-weekly
