---
#
# Ansible playbook to prepare a Bitrise OS X VM/box, used through vagrant
#

- hosts: all
  become_method: sudo
  any_errors_fatal: true
  vars:
    - param_user: vagrant
    - XCODE_INSTALL_USER: <DEFINE THIS>
    - XCODE_INSTALL_PASSWORD: <DEFINE THIS>
  roles:
    - role: profiles
    - role: brew
    - role: brew-repos-fix
    - role: xcode
