---
#
# Ansible playbook to prepare a Bitrise OS X VM/box, used through vagrant
#

- hosts: all
  become_method: sudo
  any_errors_fatal: true
  vars:
    param_user: vagrant
    param_group: staff
    password_of_param_user: vagrant
  roles:
    - role: profiles
    - role: baseos
    - role: git
    - role: xamarin
      when: is_xamarin == true
    - role: brew
    - role: brew-repos-fix
    - role: flutter
    - role: python
    - role: certs
    - role: spotlight
    - role: keychain
    - role: enable-auto-login
    - role: go
    - role: bitrise-specific-folders
    - role: bitrise-cli
    - role: bitrise-agent
    - role: remote-access
    - role: ssh-setup
    - role: cmd-bridge
    - role: brew-packages
    - role: firebase
    - role: node
    - role: jenv
    - role: ruby
    - role: ruby-gems
    - role: simulators
    - role: xcode-tools
    - role: brew-cleanup-weekly
    # - role: used-tools // exclude until android-ndk path scan is fixed
