---
#
# Ansible playbook to prepare a Bitrise OS X VM/box, used through vagrant
#

- hosts: all
  become_method: sudo
  any_errors_fatal: true
  vars:
    param_user: vagrant
    param_group: staff
    password_of_param_user: vagrant
  roles:
    - role: profiles
    - role: baseos
    - role: xamarin
      when: is_xamarin == true
    - role: brew
    - role: brew-repos-fix
    - role: flutter
    - role: python
    - role: certs
    - role: spotlight
    - role: keychain
    - role: enable-auto-login
    - role: go
    - role: bitrise-cli
    - role: bitrise-den
    - role: remote-access
    - role: ssh-setup
    - role: intermediate-setup
    - role: cmd-bridge
    - role: misc-setup
    - role: node
    - role: ruby
    - role: ruby-gems
    - role: simulators
    - role: weekly-update-shared
    - role: used-tools
