---
#
# Ansible playbook to prepare a Bitrise OS X VM/box, used through vagrant
#

- hosts: all
  become_method: sudo
  any_errors_fatal: true
  vars:
    - param_user: vagrant
    - param_group: staff
    - bitrise_cli_version: "1.43.0"
  environment:
    - GITHUB_ACCESS_TOKEN: # define this value
    - BITRISE_DEN_VERSION: "32305174"  # 1.15.1
  roles:
    - role: profiles
    - role: certs
    - role: brew
    - role: brew-repos-fix
    - role: go
    - role: bitrise-cli
    - role: bitrise-den
    - role: remote-access
    - role: ssh-setup
    - role: intermediate-setup
    - role: xcode-setup
    - role: cmd-bridge
    - role: misc-setup
    - role: node
    - role: ruby-gems
    - role: weekly-update-shared
