---
#
# Ansible playbook to prepare a Bitrise OS X VM/box, used through vagrant
#

- hosts: all
  # accelerate: true
  remote_user: vagrant
  become_method: sudo
  any_errors_fatal: True
  vars:
    - ansible_sudo_pass: vagrant
    - param_user: vagrant
    - bitrise_cli_version: 1.30.0
  roles:
    - role: profiles
    - role: ssh-setup
    - role: weekly-update-shared
    - role: xamarin
      when: is_allow_weekly_xamarin_provision | default("no") | string  == "yes"
    - role: java
    - role: jenv
    - role: android
      tags: java-android
    - role: android-sdk-packages
    - role: java-tools
      tags: java-android
    - role: flutter
