---
#
# Ansible playbook to prepare a Bitrise OS X VM/box, used through vagrant
#

- hosts: all
  # accelerate: true
  remote_user: vagrant
  vars:
    - ansible_sudo_pass: vagrant
    - param_user: vagrant
  tasks:
    #
    # Required param checks


    #
    # Setup profiles

    # Check if Android NDK is in the correct directory
    - name: Check NDK directory
      stat:
        path: "/Users/{{ param_user }}/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle"
      register: android_ndk_dir
      failed_when: not android_ndk_dir.stat.exists or not android_ndk_dir.stat.isdir

    # The main Xamarin profile, includes
    #  the Xamarin specific environments
    - name: setup xamarin_profile
      copy: src=profiles/xamarin_profile
        dest="/Users/{{ param_user }}/.profiles/xamarin_profile"
        owner="{{ param_user }}"
        mode=0600

    # Java 8 install
    # We need Java 8 because sdkmanager doesn't support newer Java versions (yet)
    # Also we need to manually call launchctl because otherwise it breaks the brew uninstall task
    - name: Stop Java's Helper-Tool
      shell: launchctl remove com.oracle.java.Helper-Tool
      become: yes
      ignore_errors: yes
    - name: Stop Java's Java-Updater
      shell: launchctl remove com.oracle.java.Java-Updater
      become: yes
      ignore_errors: yes
    - name: brew uninstall latest java
      homebrew_cask: name=java state=absent
    - name: brew tap homebrew/cask-versions
      homebrew_tap: name='homebrew/cask-versions' state=present
    - name: brew install java8
      homebrew_cask: name=java8 state=present

    # ------------------------------------------------------
    # --- Install Android SDKs and other build packages

    # Other tools and resources of Android SDK
    #  you should only install the packages you need!

    - name: install android tools
      shell: "(echo y | sdkmanager '{{ item }}') || (echo y | sdkmanager '{{ item }}')"
      loop:
        - "emulator"
        - "tools"
        - "platform-tools"
        - "platforms;android-28"
        - "platforms;android-27"
        - "platforms;android-26"
        - "platforms;android-25"
        - "platforms;android-24"
        - "platforms;android-23"
        - "platforms;android-22"
        - "platforms;android-21"
        - "platforms;android-19"
        - "platforms;android-17"
        - "platforms;android-15"
        - "build-tools;28.0.3"
        - "build-tools;28.0.2"
        - "build-tools;28.0.1"
        - "build-tools;28.0.0"
        - "build-tools;27.0.3"
        - "build-tools;27.0.2"
        - "build-tools;27.0.1"
        - "build-tools;27.0.0"
        - "build-tools;26.0.2"
        - "build-tools;26.0.1"
        - "build-tools;25.0.3"
        - "build-tools;24.0.3"
        - "build-tools;23.0.3"
        - "build-tools;22.0.1"
        - "build-tools;21.1.2"
        - "build-tools;19.1.0"
        - "build-tools;17.0.0"
        - "system-images;android-28;google_apis;x86"
        - "system-images;android-26;google_apis;x86"
        - "system-images;android-25;google_apis;armeabi-v7a"
        - "system-images;android-24;default;armeabi-v7a"
        - "system-images;android-22;default;armeabi-v7a"
        - "system-images;android-19;default;armeabi-v7a"
        - "extras;android;m2repository"
        - "extras;google;m2repository"
        - "extras;google;google_play_services"
        - "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
        - "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.1"
        - "add-ons;addon-google_apis-google-23"
        - "add-ons;addon-google_apis-google-22"
        - "add-ons;addon-google_apis-google-21"

    #
    # Install debug.keystore
    # $HOME/.local/share/Xamarin/Mono for Android/debug.keystore
    - name: "ensure Xamarin debug.keystore dir exists"
      file: path="/Users/{{ param_user }}/.local/share/Xamarin/Mono for Android"
        state=directory
        owner="{{ param_user }}"
        mode=0755
    - name: install debug.keystore
      copy: src=xamarin/debug.keystore
        dest="/Users/{{ param_user }}/.local/share/Xamarin/Mono for Android/debug.keystore"
        owner="{{ param_user }}"
        mode=0644

    #
    # Setup Bitrise specific folders
    #
    # Setup the base folders / paths, referenced by ~/.profiles/xamarin_profile
    # These folders will be created in the HOME directory.
    - name: Create bitrise xamarin specific dirs
      file: path="/Users/{{ param_user }}/{{ item.fold_path }}"
        state=directory
        owner="{{ param_user }}"
      with_items:
        # Xamarin tools
        - { fold_path: 'bitrise/xamarin' }

    - name: sync xamarin tools from the provisioning repo
      synchronize: src=xamarin/ dest="/Users/{{ param_user }}/bitrise/xamarin/"

    # Final debug prints
    - debug: msg="---> Finished with automatic stuff - but here's some things you have to do manually:"
    - debug: msg=" (!) After you finished with the preparations RESTART the machine!"
    - debug: msg=" (!) Don't forget to remove the VM snapshots (if you used snapshots) before packaging!"
    - debug: msg="---> Finished"
