---
apktools_path: /opt/apktools
aapt2_source: https://dl.google.com/dl/android/maven2/com/android/tools/build/aapt2/3.5.0-5435860/aapt2-3.5.0-5435860-osx.jar  # yamllint disable-line rule:line-length
