---
- name: Create ANDROID_NDK_HOME directory
  become: true
  file:
    path: "{{ android_ndk_home }}"
    state: directory
    owner: "{{ param_user }}"
    mode: "0770"
    recurse: true

- name: Download and unzip Android NDK into temporary location
  become: true
  unarchive:
    src: "{{ android_ndk_source }}"
    dest: "/tmp/"
    owner: "{{ param_user }}"
    mode: "0770"
    remote_src: true

- name: Copy Android NDK files to NDK home
  copy:
    src: "/tmp/android-ndk-{{ android_ndk_version }}/"
    dest: "{{ android_ndk_home }}"
    owner: "{{ param_user }}"
    mode: "0770"
    remote_src: true
  become: true

- name: Create profile.d directory
  file:
    path: "{{ ansible_env.HOME }}/profile.d"
    state: directory
    owner: "{{ param_user }}"

- name: Generate script to profile.d
  become: true
  template:
    src: patch.j2
    dest: "{{ ansible_env.HOME }}/profile.d/android.sh"
    owner: "{{ param_user }}"
    mode: "0755"

- name: ensure android directory exists
  become: true
  file:
    dest: "{{ android_home }}/cmdline-tools/"
    state: directory
    mode: "0755"

- name: Download and extract command-line tools for Android
  become: true
  unarchive:
    src: "{{ android_cmdline_tools_source }}"
    dest: "{{ android_home }}/cmdline-tools/"
    remote_src: true

- name: Ensure .android directory exists
  file:
    dest: "{{ ansible_env.HOME }}/.android/"
    state: directory

- name: Touch repositories.cfg
  copy:
    content: ""
    dest: "{{ ansible_env.HOME }}/.android/repositories.cfg"
    force: false
    mode: "0777"

- name: Install SDKs
  include_tasks:
    file: sdk-install.yml
  with_items:
    - "{{ sdkmanagerpackages }}"
  loop_control:
    loop_var: sdk

- name: Recursively change ownership of ANDROID_HOME on Xcode
  become: true
  file:
    path: "{{ android_home }}"
    recurse: true
    owner: "{{ param_user }}"
    group: staff
    mode: '0755'

- name: accept SDK licenses
  environment:
    PATH: "{{ android_home }}/cmdline-tools/cmdline-tools/bin:{{ ansible_env.PATH }}"
  shell: bash -l -c "yes | sdkmanager --licenses"  # noqa risky-shell-pipe no-changed-when

...
