---
- name: Install Android packages with SDK Manager
  become: yes
  environment:
    PATH: "/Users/{{ param_user }}/Library/Developer/Xamarin/android-sdk-macosx/tools/bin:{{ android_home }}/tools/bin:{{ ansible_env.PATH }}"
  shell: "(echo y | sdkmanager '{{ item }}') || (echo y | sdkmanager '{{ item }}')" # noqa 306 Shells that use pipes should set the pipefail option
  loop:
    - "emulator"
    - "tools"
    - "platform-tools"
    - "platforms;android-29"
    - "platforms;android-28"
    - "platforms;android-27"
    - "platforms;android-26"
    - "platforms;android-25"
    - "platforms;android-24"
    - "platforms;android-23"
    - "platforms;android-22"
    - "platforms;android-21"
    - "platforms;android-19"
    - "platforms;android-17"
    - "platforms;android-15"
    - "build-tools;29.0.3"
    - "build-tools;29.0.2"
    - "build-tools;29.0.1"
    - "build-tools;29.0.0"
    - "build-tools;28.0.3"
    - "build-tools;28.0.2"
    - "build-tools;28.0.1"
    - "build-tools;28.0.0"
    - "build-tools;27.0.3"
    - "build-tools;27.0.2"
    - "build-tools;27.0.1"
    - "build-tools;27.0.0"
    - "build-tools;26.0.2"
    - "build-tools;26.0.1"
    - "build-tools;25.0.3"
    - "build-tools;24.0.3"
    - "build-tools;23.0.3"
    - "build-tools;22.0.1"
    - "build-tools;21.1.2"
    - "build-tools;19.1.0"
    - "build-tools;17.0.0"
    - "system-images;android-29;google_apis;x86"
    - "system-images;android-28;google_apis;x86"
    - "system-images;android-26;google_apis;x86"
    - "extras;android;m2repository"
    - "extras;google;m2repository"
    - "extras;google;google_play_services"
    - "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
    - "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.1"
    - "add-ons;addon-google_apis-google-23"
    - "add-ons;addon-google_apis-google-22"
    - "add-ons;addon-google_apis-google-21"

- name: Recursively change ownership of ANDROID_HOME
  become: yes
  file:
    path: "{{ android_home }}"
    state: directory
    recurse: yes
    owner: "{{ param_user }}"
    group: staff
...
