---
- name: Download flutter from stable channel
  unarchive:
    src: https://storage.googleapis.com/flutter_infra/releases/stable/macos/flutter_macos_v{{ flutter_version }}-stable.zip
    dest: "{{ flutter_home }}"
    mode: 0770
    remote_src: yes
    owner: vagrant
    group: admin
  become: yes

- name: Creates profile.d directory
  file:
    path: $HOME/profile.d
    state: directory
    owner: vagrant
    group: vagrant
    mode: 0660

- name: Create patch.sh to profile.d
  template:
    src: patch.j2
    dest: $HOME/profile.d/flutter_patch.sh
    owner: vagrant
    group: vagrant
    mode: 0770

- name: Run flutter precache
  shell: bash -l -c "{{ flutter_home }}/flutter/bin/flutter precache"

- name: Run flutter doctor
  shell: bash -l -c "{{ flutter_home }}/flutter/bin/flutter doctor"
...
