---
- name: load simulator versions
  include_vars: "{{ xcode_version }}.yml"

- name: Install simulators
  include: install.yml
  with_items:
    - "{{ simulators }}"
  loop_control:
    loop_var: item

# iOS Simulator list. Call it at least once to initialize these.
# It seems since Xcode 8.3 only the first run
# initializes the Simulator UDIDs, if we don't call it
# during provisioning the UDIDs will change for every boot
# and `xcrun simctl list` will take quite some time (~60 seconds).
- name: xcrun simctl list
  shell: bash -l -c "xcrun simctl list"
  become: true

- name: Cleanup cached downloads
  shell: bash -l -c "xcversion cleanup"
  environment:
    XCODE_INSTALL_USER: "{{ XCODE_INSTALL_USER }}"
    XCODE_INSTALL_PASSWORD: "{{ XCODE_INSTALL_PASSWORD }}"
    FASTLANE_SESSION: "{{ FASTLANE_SESSION | b64decode }}"
