---
- name: Check if spotlight is disabled
  become: true
  shell: launchctl list | grep -q com.apple.metadata.mds
  register: spotlight_state_catalina
  changed_when: false
  ignore_errors: true

- name: Disable spotlight
  include_tasks:
    file: disable-spotlight.yml
  when: spotlight_state.rc == 1
...
