---
gem_packages:
  - name: "cocoapods"
    version: "1.10.0"
  - name: "xcpretty"
    version: "0.3.0"
  - name: "bundler"
    version: "2.1.4"
  - name: "fastlane"
    version: "2.166.0"
  - name: "xcov"
    version: "1.7.5"
  - name: "jazzy"
    version: "0.13.6"
