---
- name: brew install formulas
  homebrew:
    name: "{{ item.name }}"
    state: present
  with_items:
    - "{{ brew_packages }}"

- name: "run git lfs install"
  shell: bash -l -c 'git lfs install'

- name: Add ansible.cfg to add some settings
  copy:
    src: ansible.cfg
    dest: "{{ ansible_dest }}"

# curl used in place of get_url or uri module
# Shells that use pipes should set the pipefail option
- name: "Firebase (CLI)"  # noqa 303 306
  shell: bash -l -c "curl -sL firebase.tools | bash"
  become: true

# Setup Bitrise specific folders:
# Setup the base folders / paths, referenced by ~/.profiles/bitrise_profile
# These folders will be created in the HOME directory.
- name: Setup Bitrise specific folders
  file:
    path: "{{ bitrise_specific_folder_path }}"
    state: directory
    owner: "{{ param_user }}"
  with_items:
    - "{{ bitrise_specific_folders }}"
