---
# install additional ruby versions
- name: Install ruby 2.5.3
  shell: bash -l -c "rbenv install --skip-existing 2.5.3"
  when: is_incremental_setup|default(false) == false
- name: Install ruby 2.4.5
  shell: bash -l -c "rbenv install --skip-existing 2.4.5"
  when: is_incremental_setup|default(false) == false

- gem: # noqa 502 All tasks should be named
    name: "{{ item }}"
    state: latest # noqa 403 Package installs should not use latest
    executable: "/Users/{{ param_user }}/.rbenv/shims/gem"
    user_install: no
  loop:
    - "cocoapods"
    - "nomad-cli"
    - "xcpretty"

# GEMs: Cocoapods
- name: pod setup
  shell: bash -l -c "pod setup || pod setup"
  when: is_incremental_setup|default(false) == false
- name: CocoaPods specs install with pod
  shell: bash -l -c "pod repo add master https://github.com/CocoaPods/Specs.git"
  when: is_incremental_setup|default(false) == false and is_ci|default(false) != "true"
# The pod repo add just clone the repository. Cocopods master is huge, and we need the HEAD only so we clone that during CI run.
- name: CocoaPods specs install with git
  shell: bash -l -c "git clone --depth=1 https://github.com/CocoaPods/Specs.git ~/.cocoapods/repos/master"
  when: is_incremental_setup|default(false) == false and is_ci|default(false) == "true"

# brew some commands
- name: brew install git
  homebrew: name=git state=present
- name: brew install wget
  homebrew: name=wget state=present
- name: brew install mercurial
  homebrew: name=mercurial state=present
- name: brew install node
  homebrew: name=node@10 state=present # Node LTS 10.x
- name: brew link node@10
  command: /usr/local/bin/brew link --overwrite --force node@10 # force link Node LTS 10.x
- name: brew install ansible
  homebrew: name=ansible state=present
- name: brew install coreutils
  homebrew: name=coreutils state=present
- name: brew install watchman
  homebrew: name=watchman state=present
- name: brew install flow
  homebrew: name=flow state=present
- name: brew install tree
  homebrew: name=tree state=present
- name: brew install carthage
  homebrew: name=carthage state=present
- name: brew install imagemagick
  homebrew: name=imagemagick state=present
- name: brew install ghostscript
  homebrew: name=ghostscript state=present
- name: brew install yarn
  homebrew: name=yarn state=present
- name: brew install screen
  homebrew: name=screen state=present
- name: brew install readline
  homebrew: name=readline state=present

- name: Add ansible.cfg to add some settings
  copy: src=ansible.cfg
    dest="/Users/{{ param_user }}/ansible.cfg"

- name: brew install java
  homebrew_cask: name=java state=present

# curl used in place of get_url or uri module
# Shells that use pipes should set the pipefail option
- name: "Firebase (CLI)" # noqa 303 306
  shell: bash -l -c "curl -sL firebase.tools | bash"
  become: yes

## Go
# Gopath is $HOME/go
- name: brew install go
  homebrew: name=go state=present
- name: prepare GOPATH dirs
  file: path="/Users/{{ param_user }}/go/{{ item.fold_path }}"
    state=directory
    owner="{{ param_user }}"
  with_items:
    - { fold_path: 'src' }
    - { fold_path: 'bin' }
    - { fold_path: 'pkg' }

# NPM global packages
- name: Install "ionic", "cordova" and "appcenter-cli" NodeJS packages globally
  shell: bash -l -c "npm install -g ionic cordova appcenter-cli"

# Git LFS
- name: "brew install git lfs"
  homebrew: name=git-lfs state=present
- name: "run git lfs install"
  shell: bash -l -c 'git lfs install'

#
# Setup Bitrise specific folders
#
# Setup the base folders / paths, referenced by ~/.profiles/bitrise_profile
# These folders will be created in the HOME directory.
- name: Setup Bitrise specific folders
  file: path="/Users/{{ param_user }}/{{ item.fold_path }}"
    state=directory
    owner="{{ param_user }}"
  with_items:
    # BITRISE_SOURCE_DIR
    - { fold_path: 'git' }
    # BITRISE_STEP_DIR
    - { fold_path: 'stepdir' }
    # BITRISE_DEPLOY_DIR
    - { fold_path: 'deploy' }
    # BITRISE_LIBRARY_DIR
    - { fold_path: 'Library/MobileDevice/Provisioning Profiles' }
    # BITRISE_PROFILE_DIR
    - { fold_path: 'profiles' }
    # BITRISE_SYM_ROOT
    - { fold_path: 'build' }
    # BITRISE_OBJ_ROOT
    - { fold_path: 'bin' }
    # BITRISE_FOLDER_PATH
    - { fold_path: 'bitrise' }
    # BITRISE_STEP_DATA_FOLDER_PATH
    - { fold_path: 'bitrise/stepdata' }
    #
    - { fold_path: 'bitrise/tools' }

# Sync the tools/ dir
- name: Sync the tools dir
  synchronize: src=tools/ dest="/Users/{{ param_user }}/bitrise/tools/"

- name: make cmd-bridge executable
  file:
    path: $HOME/bitrise/tools/cmd-bridge/_scripts/install_launchctl_plist_for_current_user.sh
    owner: vagrant
    group: staff
    mode: '0755'
- name: set up cmd-bridge
  shell: bash -l -c "$HOME/bitrise/tools/cmd-bridge/_scripts/install_launchctl_plist_for_current_user.sh"
- name: load plist
  shell: bash -l -c "launchctl load /Users/vagrant/Library/LaunchAgents/bitrise.io.tools.cmd-bridge.plist"

#
# Install python3
- name: Install python@3
  homebrew:
    name: python@3
    state: present

# Switch to Xcode stable, the default Xcode for building
- name: Switch to Xcode stable, the default Xcode for building
  shell: bash -l -c "xcode-select --switch {{ xcode_path }}"
  become: yes

# iOS Simulator list. Call it at least once to initialize these.
# It seems since Xcode 8.3 only the first run
# initializes the Simulator UDIDs, if we don't call it
# during provisioning the UDIDs will change for every boot
# and `xcrun simctl list` will take quite some time (~60 seconds).
- name: xcrun simctl list
  shell: bash -l -c "xcrun simctl list"
  become: yes
