---
- name: Install xcode-install
  gem:
    name: xcode-install
    user_install: false
  become: true

- name: Install xcode version based on xcode_version variable, it could take a while. About an hour, so be patient.
  shell: bash -l -c "xcversion install '{{ xcode_version }}'"
  become: true
  environment:
    XCODE_INSTALL_USER: "{{ XCODE_INSTALL_USER }}"
    XCODE_INSTALL_PASSWORD: "{{ XCODE_INSTALL_PASSWORD }}"

- name: Install xcode simulators
  shell: bash -l -c "xcversion simulators --install='{{ item }}'"
  become: true
  environment:
    XCODE_INSTALL_USER: "{{ XCODE_INSTALL_USER }}"
    XCODE_INSTALL_PASSWORD: "{{ XCODE_INSTALL_PASSWORD }}"
  with_items:
    - "{{ simulators }}"
