---
- name: Fail if we are not on Catalina
  fail:
    msg: "Looks like you are trying to enable accessibility on not Catalina version of MacOS. It is not allowed because the syntax of TCC might be changed."
  when: ansible_facts['ansible_distribution'] == 'MacOSX' and ansible_facts['distribution_major_version'] == "10"

- name: Install xcode-install
  gem:
    name: xcode-install
    user_install: false
    executable: "$HOME/.rbenv/shims/gem"

- name: Install xcode version based on xcode_version variable, it could take a while. About an hour, so be patient.
  shell: bash -l -c "xcversion install '{{ xcode_version }}'"
  environment:
    XCODE_INSTALL_USER: "{{ XCODE_INSTALL_USER }}"
    XCODE_INSTALL_PASSWORD: "{{ XCODE_INSTALL_PASSWORD }}"

- name: Install xcode simulators
  shell: bash -l -c "xcversion simulators --install='{{ item }}'"
  environment:
    XCODE_INSTALL_USER: "{{ XCODE_INSTALL_USER }}"
    XCODE_INSTALL_PASSWORD: "{{ XCODE_INSTALL_PASSWORD }}"
  with_items:
    - "{{ simulators }}"

- name: Cleanup cached downloads
  shell: bash -l -c "xcversion cleanup"
  environment:
    XCODE_INSTALL_USER: "{{ XCODE_INSTALL_USER }}"
    XCODE_INSTALL_PASSWORD: "{{ XCODE_INSTALL_PASSWORD }}"

# TODO: This causes permission issues + the hardcoded simulator version could be a problem
# Needs to be solved in an upcoming sprint, commenting out so that the builds won't fail meanwhile

# - name: Git checkout
#   git:
#     repo: 'https://github.com/bitrise-io/xcode-test-apps'
#     dest: "/opt/bitrise/testapps"
#     version: 1.0

# - name: Xcodebuild iOS
#   shell: xcodebuild test -project bitrise.xcodeproj -scheme bitrise -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.2'
#   args:
#     chdir: "/opt/bitrise/testapps/bitrise"

# - name: Xcodebuild macOS
#   shell: xcodebuild test -project bitrise-mac.xcodeproj -scheme bitrise-mac -destination 'platform=macOS,arch=x86_64,id=420E1727-1771-77C5-658D-E41EAF10AE6C'
#   args:
#     chdir: "/opt/bitrise/testapps/bitrise-mac"
# TODO: We should use profiles for enable accessibility but it needs more time and investigation, will happen in the upcoming sprint

- name: Enable accessibility to xcode
  script: install_accessibility.sh
  become: true
