---
- name: brew install rbenv
  homebrew:
    name: rbenv
    state: latest  # noqa 403 Package installs should not use latest
    update_homebrew: true

- name: unlink openssl
  homebrew:
    name: openssl
    state: unlinked
  when: ansible_distribution == 'Ubuntu'

- name: Install ruby versions
  shell: bash -l -c "rbenv install --skip-existing {{ item.version }}"
  when: is_incremental_setup|default(false) == false
  with_items:
    - "{{ default_ruby }}"
    - "{{ ruby_versions }}"

- name: Set ruby latest to global
  shell: bash -l -c "rbenv global {{ default_ruby.0.version }}"
  when: is_incremental_setup|default(false) == false
